#!/bin/bash

[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
vncconfig -iconic &
xsetroot -solid grey
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

# if [ -f /etc/X11/xinit/xinitrc ]; then
#   exec sh /etc/X11/xinit/xinitrc
# fi

exec sh $HOME/.xinitrc
