#!/bin/sh

[ -r /etc/sysconfig/i18n ] && . /etc/sysconfig/i18n
export LANG
export SYSFONT

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

if [ -f /etc/X11/xinit/xinitrc ]; then
  exec sh /etc/X11/xinit/xinitrc
fi

[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

vncconfig -nowin &
xsetroot -solid grey

exec gnome-session &
